name: example
description: Example app showcasing usage of flutter_map_line_editor.
publish_to: 'none'
version: 3.0.0-beta.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.0.0-beta.1
  flutter_map_dragmarker: ^4.0.0-beta.1
  flutter_map_line_editor:
    path: ../
  latlong2: ^0.8.0

dev_dependencies:
  flutter_lints: ">=1.0.4"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
